package com.gmail.jpk.stu.Randomizer;

public enum Careers {
	DETECTIVE, DOCTOR, SCIENTIST, ASTRONAUT, ATHLETE, BUSINESS, CRIMINAL, CRTIC, CULINARY, ENTERTAINER, PAINTER, POLITICIAN, SECRET_AGENT, SOCIAL_MEDIA, TECH_GURU,
	WRITER, FREELANCE_AUTHOR, FREELANCE_MUSICIAN, FREELANCE_PAINTER, FREELANCE_PROGRAMMER;
	
	public static int getSize() {
		return Careers.values().length;
	}
}
