package com.gmail.jpk.stu.Randomizer;

public class Traits {
	
	public enum Toddler {
		ANGELIC, CHARMER, CLINGY, FUSSY, INDEPENDENT, INQUISITIVE, SILLY, WILD;
		
		public static int getSize() {
			return Toddler.values().length;
		}
	}
	
	public enum Child {
		ACTIVE, CHEERFUL, CREATIVE, GENIUS, GLOOMY, GOOFBALL, HOT_HEADED, SELF_ASSURED, ART_LOVER, BOOKWORM, GEEK, MUSIC_LOVER, PERFECTIONIST, 
		CAT_LOVER, DOG_LOVER, ERRATIC, GLUTTON, KLEPTOMANIAC, LAZY, LOVES_OUTDOOR, NEAT, SLOB, VEGETARIAN, EVIL, GOOD, INSIDER, LONER, MEAN, OUTGOING;
		
		public static int getSize() {
			return Child.values().length;
		}
	}
	
	public enum Teen {
		ACTIVE, CHEERFUL, CREATIVE, GENIUS, GLOOMY, GOOFBALL, HOT_HEADED, ROMANTIC, SELF_ASSURED, UNFLIRTY, ART_LOVER, BOOKWORM, FOODIE, GEEK, MUSIC_LOVER,
		PERFECTIONIST, CAT_LOVER, CHILDISH, CLUMSY, DANCE_MACHINE, DOG_LOVER, ERRATIC, GLUTTON, KLEPTOMANIAC, LAZY, LOVES_OUTDOOR, MATERIALISTIC, NEAT, SLOB, SNOB,
		VEGETARIAN, BRO, EVIL, GOOD, HATES_CHILDREN, INSIDER, JEALOUS, LONER, MEAN, OUTGOING;
		
		public static int getSize() {
			return Teen.values().length;
		}
	}
	
	public enum Adult {
		ACTIVE, CHEERFUL, CREATIVE, GENIUS, GLOOMY, GOOFBALL, HOT_HEADED, ROMANTIC, SELF_ASSURED, UNFLIRTY, ART_LOVER, BOOKWORM, FOODIE, GEEK, MUSIC_LOVER,
		PERFECTIONIST, AMBITIOUS, CAT_LOVER, CHILDISH, CLUMSY, DANCE_MACHINE, DOG_LOVER, ERRATIC, GLUTTON, KLEPTOMANIAC, LAZY, LOVES_OUTDOOR, MATERIALISTIC, NEAT, SLOB, SNOB,
		VEGETARIAN, BRO, EVIL, FAMILY_ORIENTED, GOOD, HATES_CHILDREN, INSIDER, JEALOUS, LONER, MEAN, NON_COMMITAL, OUTGOING;
		
		public static int getSize() {
			return Adult.values().length;
		}
	}
}
